# This workflow labels issues with proper bugs

name: Issues Labeler
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  triage_labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "needs-triage"
          ignore-if-labeled: true
          ignore-if-assigned: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
