# This workflow will triage issues and apply a label on the opened/reopened issues
#
# To use this workflow, you will need to set up a .github/workflows/label_bugs.yml
# file with configuration.  For more information, see:
# https://github.com/github/issue-labeler

name: "Issue Labeler"
on:
  issues:
    types: [opened, reopened]
jobs:
  needs-triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.0
      with:
        enable-versioned-regex: 0
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/workflows/label_bugs.yml
